import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import { TicketsProvider } from "@/provider/TicketContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <TicketsProvider>
            <NavBar />
            <div className="min-h-screen max-w-full basis-full overflow-scroll flex flex-center">
              {children}
            </div>
            <Footer />
          </TicketsProvider>
        </main>
      </body>
    </html>
  );
}
